### ISSUE TITLE
ImportError: No module named 'telegram'

### ISSUE THREAD

**Issue by janssenlima** [juliarizza/helpdeskbot#4]
Mesmo instalando as dependências está ocorrendo o erro abaixo (rodando com Python 3):

```
>>> from main import updater
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/helpdeskbot/main.py", line 2, in <module>
    import telegram
ImportError: No module named 'telegram'
```

Quando rodo com Python 2.7, o erro muda para:

```
>>> from main import updater
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "main.py", line 9, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler,\
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py", line 29, in <module>
    from telegram import (TelegramError, NullHandler)
ImportError: cannot import name TelegramError
```

**Comment by juliarizza** [comment]
O script é feito para ser executado em Python 3, mas você instalou o python-telegram-bot no Python 2. Como você tem ambas as versões, e o 2 deve ser seu padrão, instale no Python 3 usando:

`pip3 install -r requirements`
